site_name: Board Game Teaches

# site structure
nav:
  - Home: 
    - index.md
    - to_do_list.md
  - Big Games:
    - Agricola: big_games/agricola.md
    - Ants: big_games/ants.md
    - Black Forest: big_games/black_forest.md
    - Bus: big_games/bus.md
    - Calimala: big_games/calimala.md
    - Cuzco: big_games/cuzco.md
    - Darwin's Journey: big_games/darwins_journey.md
    - Druids of Edora: big_games/druids_of_edora.md
    - Evacuation: big_games/evacuation.md
    - Five Tribes: big_games/five_tribes.md
    - Gaia Project: big_games/gaia_project.md
    - Great Western Trail: big_games/great_western_trail.md
    - Inferno: big_games/inferno.md
    - Lightning Train: big_games/lightning_train.md
    - Lisboa: big_games/lisboa.md
    - Lorenzo Il Magnifico: big_games/lorenzo.md
    - Ostia: big_games/ostia.md
    - Railways of the Lost Atlas: big_games/lost_atlas.md
    - Rajas of the Ganges: big_games/rajas.md
    - Recall: big_games/recall.md
    - Red Cathedral: big_games/red_cathedral.md
    - Revive: big_games/revive.md
    - Shipyard: big_games/shipyard.md
    - Tianxia: big_games/tianxia.md
    - Tiletum: big_games/tiletum.md
    - Trickerion: big_games/trickerion.md
    - Unconcious Mind: big_games/unconcious_mind_template.md
    - Voayags of Marco Polo: big_games/marco_polo.md
    - Zapotec: big_games/zapotec.md
  - Card Games:
    - Bid Coin: card_games/bid_coin.md
    - Depot: card_games/depot.md
    - Dokitto! Ice: card_games/dokitto_ice.md
    - Live Mix: card_games/livemix.md
    - Savage Bowl: card_games/savage_bowl.md
    - Segnum: card_games/segnum.md
    - Sumida River: card_games/sumida_river.md
    - Tabletop Climber: card_games/tabletop_climber.md
    - Tornei: card_games/tornei.md
    - Twinkle Starship: card_games/twinkle_starship.md
  - Con Games:
    - Feed the Kraken: con_games/feed_the_kraken.md

# theme
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.tabs.link

markdown_extensions:
  - attr_list  # Allows adding HTML-style attributes like {.class}
  - md_in_html # Allows Markdown inside raw HTML blocks (like <div>)
  - admonition
 # - codehilite
 # - toc:
 #   permalink: true
 # - pymdownx.superfences
 # - pymdownx.tabbed
